version: "3.5"


services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: Dhanush97
      POSTGRES_USER: sanju
      POSTGRES_DB: core
    volumes:
      - eat-bear-core:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  eat-bear-core:

